index:
    path: /
    controller: App\Controller\MainController::indexAction
contact:
    path: /contact
    controller: App\Controller\MainController::Contact

notfind:
    path: /notfond
    controller: App\Controller\MainController::notfond







