index:
    path: /
    controller: App\Controller\MainController::indexAction
contact:
    path: /contact
    controller: App\Controller\MainController::Contact

list_service:
      path : /user/formation
      defaults: {_controller: App\User\}





